# Generated by Django 4.0.3 on 2022-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userinfo_email_userinfo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
